# Generated by Django 5.1.2 on 2024-10-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_tires_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tires',
            name='promotion',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Акция'),
        ),
    ]
